[project]
name = "vnmutils"
version = "0.0.4"
description = "Shared utilities for Vinaya Notes Module builders"
authors = [
  { name="Khemarato Bhikkhu" }
]
requires-python = ">=3.8"
dependencies = [
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

